
= Multithreading & Synchronisation

== Überblick

Dieser Teil stellt verschiedene Möglichkeiten für Multithreading in Rust vor.

Benötigt wird nur die `std`. Eine Einführung gibt es hier: https://doc.rust-lang.org/book/ch16-00-concurrency.html[Multithreading]

Synchronisationsprimitiven sind im Modul https://doc.rust-lang.org/std/sync/#structs[std::sync] zu finden, welche wir uns hier anschauen.

== Übung scoped-threads
Hier möchten wir und gleich dem Thema zuwenden, wie man in untergeordneten Threads mit begrenzer Lebenszeit auf lokale Variablen zugreifen kann.

Hierzu schauen wir uns das Beispiel `scoped-threads` an.

Erstelle hierzu ein Programm, welches mit `thread::scope` einen thread spawn macht.

== Zugriff auf statische 'Werte'

Wir reden hier vom 'storage class spezifier' static.
Die Werte können auch als `mut` deklariert werden. Rust schränkt dann den Zugriff auf Werte
https://doc.rust-lang.org/reference/items/static-items.html#mutable-statics

Welche Möglichkeiten gibt es für den Zugriff und die Initialisierung?

== Once

https://doc.rust-lang.org/std/sync/struct.Once.html[Once] eignet sich, wenn man z.B. eine Bibliothek, z.B. ein FFI schreibt, und sicherstellen will, dass Initialisierungscode nur genau einmal druchlaufen wird, egal von wie vielen Threads aus die Bibliothek verwendet wird, also man keine Kontrolle über die Aufrufer hat.
Schreibe ein Test, welcher 2 threads startet, und call_once zweimal aufruft. Prüfe, ob die Initialisierungsmethode nur eimal aufgeführt wird
[Note] 
====
Gezielt kann an einen einzeln Test mit println! Ausgabe so starten:

 cargo test once_lambda_is_called_only_once -- --show-output
====
=== OnceCell

Mit der OnceCell können nur lokale Variablen initialisiert werden, da OnceCell !Sync ist.
https://doc.rust-lang.org/std/cell/struct.OnceCell.html
Scheibe einen Test dazu.

== OnceLock

Mit OnceLock können statische Variablen threadsicher initialisiert werden.
Schreibe einen Test, der 2 threads started, wartet und dann den Wert prüft
let

* std::cell::OnceCell
* once_cell::unsync::OnceCell?
* once_cell::sync::Lazy

Most of this crate’s functionality is available in std starting with Rust 1.70. See std::cell::OnceCell and std::sync::OnceLock.

[Note]
====
Wenn man no_std verwenden muss, kann man die Typen std::sync::OnceLock nicht verwenden, da bleibt nur die Alternative https://docs.rs/once_cell/latest/once_cell/#faq
====

https://docs.rs/once_cell/latest/once_cell/sync/struct.Lazy.html
https://docs.rs/once_cell/latest/once_cell/unsync/struct.Lazy.html

Ebenso, lazy_static crate und das macro lazy_static!

== Embedded Rust und no_std

Wer Rust auf embbeded systems einsetzen möchte, z.B. bare Metal, d.h. ohne Betriebsystem, muss auf std verzichten.
Wer mehr erfahren möchte liest hier nach:

* https://docs.rust-embedded.org/book/intro/index.html[embedded rust]
* https://tweedegolf.nl/en/blog/96/why-rust-is-a-great-fit-for-embedded-software-2023-update[why is rust good for embedded software] enthält auch Links auf Hersteller, die Rust support anbieten.

== Lesen und Schreiben

Wenn man lesenden und schreibenden Zugriff von mehreren Threads auf einen Wert braucht, kann man https://doc.rust-lang.org/std/sync/struct.RwLock.html[`std::sync::RwLock`] verwenden:
Schreibe ein Test, welcher mehrere Threads erzeugt, und einen gemeinsamen Wert ändert.

[Note]
====
Verwende https://doc.rust-lang.org/std/ops/struct.Range.html[Ranges] (0u8..5u8) um über die Zahlen 0 bis 4 zu iterieren.
Erzeuge je einen Thread pro Zahl.
Jeder Thread fügt einen Buchstaben zu dem gemeinsam String hinzu.

* Thread 0: 'a', 
* Thread 1: 'b'...
====

== Optionale Übung: Wechselseitiger Ausschluss Mutex

Ähnlich wie RwLock bietet std::sync::Mutex den wechselseitigen Ausschluss, unterscheidet jedoch nicht zwischen Lesen und Schreiben.

Ersetze in der vorigen Übung RwLock durch Mutex.

== Kommunikation mit Channels (sync::mpsc)

Anstatt sich über shared memory auszutauschen, kann man Nachrichten verschicken. In dieser Übung bauen wir einen Nachrichtenkanal auf.
Die Grundlagen haben wir hier: https://doc.rust-lang.org/book/ch16-02-message-passing.html

== Threads aufwecken mit sync::CondVar

Falls ein Thread auf etwas warten muss, was z.B. über ein Mutex synchroniert wird, eigenet sich einen CondVar. 
Sie wird überlicherweise als Paar (Mutex, CondVar) verwendet. Die CondVar gibt währed der Wartezeit den Mutex frei, und fordert ihn vor der Rückkehr wieder an.

https://doc.rust-lang.org/std/sync/struct.Condvar.html#

Scheibe ein Beispiel hierzu.
